fixtures:
  repositories:
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    rspec-pupet-facts: "https://github.com/mcanevet/rspec-puppet-facts"
  symlinks:
    logstash: "#{source_dir}"
